FideGames/Models/deparment_product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FideGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deparment_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public deparment_product()
        {
            this.product = new HashSet<product>();
        }
    
        public int deparment_product_id { get; set; }
        public string deparment_product_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> product { get; set; }
    }
}

FideGames/Controllers/Deparment_productController.cs
using FideGames.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FideGames.Controllers
{
    public class Deparment_productController : Controller
    {
        // GET: Deparment_product
        Models.proyectoFideGamesEntities1 db = new proyectoFideGamesEntities1();
        // Listar Marcas
        public ActionResult Listadeparment_product()
        {
            IEnumerable<deparment_product> list = db.deparment_product.ToList();
            return View(list);
        }

        //crear marca
        public ActionResult Creardeparment_product()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Creardeparment_product([Bind(Include = "deparment_product_id,deparment_product_Name")] deparment_product deparment_Product)
        {
            if (ModelState.IsValid)
            {
                db.deparment_product.Add(deparment_Product);
                db.SaveChanges();
                ViewBag.exito = "Se ha agregado el nuevo departamento de productos";
            }
            return RedirectToAction("Listadeparment_product");
        }

        // Detalles de departamento
        public ActionResult Detallardeparment_product(int id)
        {
            deparment_product deparment_Product = db.deparment_product.Find(id);
            return View(deparment_Product);
        }
        public ActionResult Editardeparment_product(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            deparment_product deparment_Product = db.deparment_product.Find(id);
            if (deparment_Product == null)
            {
                return HttpNotFound();
            }
            return View(deparment_Product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editardeparment_product([Bind(Include = "deparment_product_id,deparment_product_Name")] deparment_product deparment_Product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(deparment_Product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Listadeparment_product");
            }
            return View(deparment_Product);
        }
        //Eliminar marca
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminardeparment_product(deparment_product deparment_Product)
        {
            db.Entry(deparment_Product).State = System.Data.Entity.EntityState.Deleted;
            db.SaveChanges();
            ViewBag.exito = "Se ha eliminado el departamento de productos";
            return RedirectToAction("Listadeparment_product");

        }
    }
}

FideGames/Views/Deparment_product/Creardeparment_product.cshtml
@model FideGames.Models.deparment_product

@{
    ViewBag.Title = "Creardeparment_product";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@if (ViewBag.error == "" | ViewBag.error == null)
{

}
else
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <span class="aria-hidden">@ViewBag.error</span>
    </div>

}
<div class="card-body card shadow mb-4">
    <style>
        .card-title {
            padding-bottom: 15px;
            background: #040FD9;
            color: #fff;
            padding: 16px 30px;
            min-width: 100%;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }
    </style>
    <div class="card-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>Creacion de departamento de productos</h2>
            </div>
        </div>
    </div>
    @using (Html.BeginForm("Creardeparment_product", "Deparment_product", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Roles</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="text-dark">Nombre de Departamento</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.deparment_product_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.deparment_product_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Crear" class="btn btn-primary" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Mostrar lista de departamentos de productos", "Listadeparment_product")
                </div>
            </div>
        </div>
    }

</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

FideGames/Views/Deparment_product/Detallardeparment_product.cshtml
@model FideGames.Models.deparment_product

@{
    ViewBag.Title = "Detallardeparment_product";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@if (ViewBag.Mensaje == "" | ViewBag.Mensaje == null)
{
}
else
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <strong>Exitoso!</strong>
        <span class="aria-hidden">@Html.ViewBag.Mensaje</span>
    </div>

}
<div class="card-body card shadow mb-4">
    <style>
        .card-title {
            padding-bottom: 15px;
            background: #040FD9;
            color: #fff;
            padding: 16px 30px;
            min-width: 100%;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }
    </style>
    <div class="card-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>Detalles del departamento de productos</h2>
            </div>
        </div>
    </div>

    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="form-group">
            <div class="col-md-10">
                <label class="text-dark">Nombre del departamento</label>
                <input disabled class="form-control" id="colFormLabel" placeholder="@Html.DisplayFor(model => model.deparment_product_name)">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.ActionLink("Editar", "Editardeparment_product", new { id = Model.deparment_product_id }, new { @class = "btn btn-warning" })
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                    Eliminar
                </button>
            </div>
            <div class="col-md-10 mt-3">
                @Html.ActionLink("Mostrar lista de departamentos de productos", "Listadeparment_product")
            </div>
        </div>

    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    <i class="fas fa-exclamation-triangle" style="color:red;"></i>
                    Advertencia
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Esta Seguro que desea Eliminar el departamento de productos @Html.DisplayFor(model => model.deparment_product_name) ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>

                @using (Html.BeginForm("Eliminardeparment_product", "Deparment_product", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.deparment_product_id)
                    @Html.HiddenFor(model => model.deparment_product_name)

                    <div class="form-actions no-color">
                        <input type="submit" value="Eliminar" class="btn btn-danger" />
                    </div>
                }

            </div>
        </div>
    </div>
</div>

FideGames/Views/Deparment_product/Editardeparment_product.cshtml
@model FideGames.Models.deparment_product

@{
    ViewBag.Title = "Editardeparment_product";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@if (ViewBag.error == "" | ViewBag.error == null)
{

}
else
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <span class="aria-hidden">@ViewBag.error</span>
    </div>

}
<div class="card-body card shadow mb-4">
    <style>
        .card-title {
            padding-bottom: 15px;
            background: #040FD9;
            color: #fff;
            padding: 16px 30px;
            min-width: 100%;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }
    </style>
    <div class="card-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>Editar Departamento de productos</h2>
            </div>
        </div>
    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.deparment_product_id)

            <div class="form-group">
                <div class="col-md-10">
                    <label class="text-dark">Nombre de la Marca</label>
                    @Html.EditorFor(model => model.deparment_product_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.deparment_product_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar Cambios" class="btn btn-primary" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Mostrar lista de Departamentos de productos", "Listadeparment_product")
                </div>
            </div>

        </div>

    }

</div>

FideGames/Views/Deparment_product/Listadeparment_product.cshtml
@model IEnumerable<FideGames.Models.deparment_product>

@{
    ViewBag.Title = "Listadeparment_product";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@if (ViewBag.exito == "" | ViewBag.exito == null)
{

}
else
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <span class="aria-hidden">@Html.ViewBag.exito</span>
    </div>

}
@if (ViewBag.error == "" | ViewBag.error == null)
{

}
else
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <span class="aria-hidden">@ViewBag.error</span>
    </div>

}

<div class="card-body card shadow mb-4">
    <style>
        .table-title {
            padding-bottom: 15px;
            background: #040FD9;
            color: #fff;
            padding: 16px 30px;
            min-width: 100%;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }

            .table-title h2 {
                margin: 5px 0 0;
                font-size: 24px;
            }

            .table-title .btn-group {
                float: right;
            }

            .table-title .btn {
                color: #fff;
                float: right;
                font-size: 13px;
                border: none;
                min-width: 50px;
                border-radius: 2px;
                border: none;
                outline: none !important;
                margin-left: 10px;
            }
    </style>
    <div class="table-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>Departamentos de productos</h2>
            </div>
            <div class="col-sm-6">
                @Html.ActionLink("Agregar nuevo departamento de productos", "Creardeparment_product", null, new { @class = "btn btn-primary btn-lg" })
            </div>
        </div>

    </div>
    <div class="table-responsive">
        <table id="TableEmployee" class="table table-avance table-striped ">
            <thead class="table-dark">
                <tr>
                    <th class="">
                        Nombre de departamento de productos
                    </th>
                    <th class="d-flex justify-content-center ">
                        Acciones
                    </th>
                </tr>
            </thead>
            <tbody class=" ">
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.deparment_product_name)
                        </td>
                        <td class="d-flex justify-content-center ">
                            @Html.ActionLink("Editar", "Editardeparment_product", new { id = item.deparment_product_id }, new { @class = "btn btn-primary mr-2" })
                            @Html.ActionLink("Detalles", "Detallardeparment_product", new { id = item.deparment_product_id }, new { @class = "btn btn-primary mr-2" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>