FideGames/Models/invoice.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FideGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoice()
        {
            this.invoice_detail = new HashSet<invoice_detail>();
        }
    
        public int id_invoice { get; set; }
        public int user_id { get; set; }
        public int seller { get; set; }
        public byte[] date_sell { get; set; }
        public decimal sale_total { get; set; }
        public string payment_des { get; set; }
        public Nullable<int> invoice_status { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual invoice_status invoice_status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_detail> invoice_detail { get; set; }
        public virtual Users Users { get; set; }
    }
}

FideGames/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FideGames.Models;
using FideGames.Clases;

namespace FideGames.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        proyectoFideGamesEntities1 db = new proyectoFideGamesEntities1();
        invoice invoice = new invoice();
        invoice_detail details = new invoice_detail();
        invoice_status status = new invoice_status();

        // GET: Invoice
        public ActionResult Index()
        {
            IEnumerable<invoice> list = db.invoice.ToList();
            return View(list);
        }

        // GET: Invoice/Details/5
        public ActionResult Details(int id)
        {
            DetailInvoiceViewData data = new DetailInvoiceViewData();
            invoice invoice = db.invoice.Find(id);
            IEnumerable<invoice_detail> detailsList = (from invoice_detail in db.invoice_detail
                                                       where invoice_detail.id_invoice == id
                                                       select invoice_detail).ToList();
            data.invoice = invoice;
            data.invoice_detail = detailsList;

            return View(data);
        }

        // GET: Invoice/Create
        public ActionResult Create()
        {
            var clients = db.clients.ToList();
            List<SelectListItem> clientsList = new List<SelectListItem>();
            foreach (var client in clients)
            {
                clientsList.Add(new SelectListItem
                {
                    Value = client.client_id.ToString(),
                    Text = (
                    client.client_id_card + " " + client.client_name1 + " " + client.client_name2 + " " + client.client_lastname1 + " " + client.client_lastname2
                    )
                });
            }
            ViewBag.Clients = clientsList;
            ViewBag.Products = db.product.ToList();

            return View();
        }

        // POST: Invoice/Create
        [HttpPost]
        public ActionResult Create(invoice invoice)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.invoice.Add(invoice);
                    db.SaveChanges();
                    ViewBag.Mensaje = "Se ha Creado Factura";
                    return RedirectToAction("Index");
                }
                catch
                {
                    var clients = db.clients.ToList();
                    List<SelectListItem> clientsList = new List<SelectListItem>();
                    foreach (var client in clients)
                    {
                        clientsList.Add(new SelectListItem
                        {
                            Value = client.client_id.ToString(),
                            Text = (
                            client.client_id_card + " " + client.client_name1 + " " + client.client_name2 + " " + client.client_lastname1 + " " + client.client_lastname2
                            )
                        });
                    }
                    ViewBag.Clients = clientsList;
                    ViewBag.error = "Error al incluir el Dato";
                    return View();
                }
            }
            else
            {
                return Redirect("Create");
            }

        }

        public ActionResult Add(int id)
        {
            List<SelectListItem> ProductsList = new List<SelectListItem>();
            var Products = db.product.ToList();

            foreach (var product in Products)
            {
                ProductsList.Add(new SelectListItem
                {
                    Value = product.product_id.ToString(),
                    Text = (product.product_name + " Precio: ₡" + product.price)
                });
            };

            List<SelectListItem> InvoiceList = new List<SelectListItem>();
            var Invlice = db.invoice.ToList();
            foreach (var invoice in Invlice)
            {
                InvoiceList.Add(new SelectListItem
                {
                    Value = invoice.id_invoice.ToString(),
                    Text = invoice.payment_des
                });
            }

            ViewBag.Product = ProductsList;
            ViewBag.Invoice = InvoiceList;
            ViewBag.InvoiceNumber = id;
            return View();
        }

        [HttpPost]
        public ActionResult Add(invoice_detail detail)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    int id = Convert.ToInt32(detail.product_id);
                    var product = db.product.Find(id);
                    detail.product_price = product.price;
                    product.quantities = (product.quantities) - 1;
                    var invoiceUpdate = db.invoice.Find(id);
                    invoiceUpdate.sale_total = (invoiceUpdate.sale_total) + product.price;
                    db.invoice_detail.Add(detail);
                    db.Entry(product).State = System.Data.Entity.EntityState.Modified;
                    db.Entry(invoiceUpdate).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.error = "Error al incluir el Dato";
                    return View(detail.id_invoice);
                }

            }
            else
            {
                ViewBag.error = "Error en el Modelo";
                return View(detail.id_invoice);
            }


        }

        // GET: Invoice/Edit/5
        public ActionResult Edit(int id)
        {
            invoice data = db.invoice.Find(id);

            List<SelectListItem> StateList = new List<SelectListItem>();
            List<invoice_status> state = db.invoice_status.ToList();
            foreach (var item in state)
            {
                StateList.Add(new SelectListItem
                {
                    Value = item.invoice_status_id.ToString(),
                    Text = item.invoice_status_name
                });
            }

            ViewBag.Status = StateList;

            return View(data);
        }

        // POST: Invoice/Edit/5
        [HttpPost]
        public ActionResult Edit(invoice invoice)
        {
            if (true)
            {
                try

                {
                    db.Entry(invoice).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.error = "Error al incluir el Dato";
                    List<SelectListItem> StateList = new List<SelectListItem>();
                    List<invoice_status> state = db.invoice_status.ToList();
                    foreach (var item in state)
                    {
                        StateList.Add(new SelectListItem
                        {
                            Value = item.invoice_status_id.ToString(),
                            Text = item.invoice_status_name
                        });
                    }

                    ViewBag.Status = StateList;

                    return View(invoice.id_invoice);
                }
            }
            else
            {
                ViewBag.error = "Error con el Modelo";
                return View(invoice.id_invoice);
            }

        }
    }
}

FideGames/Views/Invoice/Add.cshtml
@model FideGames.Models.invoice_detail

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@if (ViewBag.exito == "" | ViewBag.exito == null)
{

}
else
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <span class="aria-hidden">@Html.ViewBag.exito</span>
    </div>

}
@if (ViewBag.error == "" | ViewBag.error == null)
{

}
else
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <span class="aria-hidden">@ViewBag.error</span>
    </div>

}

<div class="card-body card shadow mb-4">
    <style>
        .card-title {
            padding-bottom: 15px;
            background: #040FD9;
            color: #fff;
            padding: 16px 30px;
            min-width: 100%;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }
    </style>
    <div class="card-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>Incluir Producto a Factura</h2>
            </div>
        </div>
    </div>
    @using (Html.BeginForm("Add", "Invoice", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <div class="col-md-10">
                    <label class="text-dark">Factura</label>
                    <input disabled class="form-control" id="id_invoice" placeholder="FE-001-@ViewBag.InvoiceNumber">
                    @Html.HiddenFor(Model => Model.id_invoice, new { @Value = ViewBag.InvoiceNumber })

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <label class="text-dark">Producto</label>
                    @Html.DropDownListFor(model => model.product_id, (IEnumerable<SelectListItem>)ViewBag.Product, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.product_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <label class="text-dark">Cantidad</label>
                    @Html.EditorFor(model => model.quantities, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.quantities, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Incluir Producto" class="btn btn-primary mr-2" />
                </div>
            </div>
        </div>


    }
    <div>
        @Html.ActionLink("Volver a las Facturas", "Index")
    </div>

</div>

FideGames/Views/Invoice/Create.cshtml
@model FideGames.Models.invoice

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@if (ViewBag.exito == "" | ViewBag.exito == null)
{

}
else
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <span class="aria-hidden">@Html.ViewBag.exito</span>
    </div>

}
@if (ViewBag.error == "" | ViewBag.error == null)
{

}
else
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <span class="aria-hidden">@ViewBag.error</span>
    </div>

}

<div class="card-body card shadow mb-4">
    <style>
        .card-title {
            padding-bottom: 15px;
            background: #040FD9;
            color: #fff;
            padding: 16px 30px;
            min-width: 100%;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }
    </style>
    <div class="card-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>Creacion de Factura</h2>
            </div>
        </div>
    </div>
    @using (Html.BeginForm("Create", "Invoice", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-row">
                <div class="col-md-6">
                    <label class="text-dark">Vendedor</label>
                    @Html.HiddenFor(Model => Model.seller, new { @Value = HttpContext.Current.Session["id"] })
                    <input disabled type="email" class="form-control" id="inputEmail4" placeholder="@HttpContext.Current.Session["name"].ToString()">
                </div>
                <div class="col-md-6">
                    <label class="text-dark">Cliente</label>
                    @Html.DropDownListFor(Model => Model.user_id, (IEnumerable<SelectListItem>)ViewBag.Clients, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })
                </div>
                @Html.HiddenFor(Model => Model.invoice_status, new { @Value = 1 })

            </div>

            <div class="form-group">
                <div class="col-md-14">
                    <label class="text-dark">Comentarios</label>
                    @Html.EditorFor(model => model.payment_des, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.payment_des, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-14 ">
                    <div class="text-center mx-auto">
                        @Html.ActionLink("Crear Cliente", "Create", "Clients", new { @class = "btn btn-primary mr-2" })
                        <button type="submit" value="Create" class="btn btn-primary">Crear Factura</button>
                    </div>
                </div>
            </div>

        </div>
    }
    <div>
        @Html.ActionLink("Volver a las Facturas", "Index")
    </div>

</div>






<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

FideGames/Views/Invoice/Details.cshtml
@model FideGames.Clases.DetailInvoiceViewData

@{
    ViewBag.Title = "Detalles de Facturacion";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@if (ViewBag.Mensaje == "" | ViewBag.Mensaje == null)
{
}
else
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <strong>Exitoso!</strong>
        <span class="aria-hidden">@Html.ViewBag.Mensaje</span>
    </div>

}


<div class="card-body card shadow mb-4">
    <style>
        .card-title {
            padding-bottom: 15px;
            background: #040FD9;
            color: #fff;
            padding: 16px 30px;
            min-width: 100%;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }
    </style>
    <div class="card-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>Detalles del Factura</h2>
            </div>
        </div>
    </div>

    @Html.AntiForgeryToken()

    <div class="form-horizontal">


        <div class="mt-3">
            <h2>Cliente</h2>
        </div>


        <div class="form-horizontal">
            <div class="row">
                <div class="col">
                    <label class="text-dark">Nombre</label>
                    <input disabled class="form-control" id="colFormLabel" placeholder="@Html.DisplayFor(model => model.invoice.clients.client_name1) @Html.DisplayFor(model => model.invoice.clients.client_name2)">
                </div>
                <div class="col">
                    <label class="text-dark">Apellido</label>
                    <input disabled class="form-control" id="colFormLabel" placeholder="@Html.DisplayFor(model => model.invoice.clients.client_lastname1) @Html.DisplayFor(model => model.invoice.clients.client_lastname2)">
                </div>
                <div class="col">
                    <label class="text-dark">Cedula</label>
                    <input disabled class="form-control" id="colFormLabel" placeholder="@Html.DisplayFor(model => model.invoice.clients.client_id_card) ">
                </div>
                <div class="col">
                    <label class="text-dark">Email</label>
                    <input disabled class="form-control" id="colFormLabel" placeholder="@Html.DisplayFor(model => model.invoice.clients.client_email) ">
                </div>
            </div>

            <div class="mt-3">
                <h2>Factura</h2>
            </div>

            <div class="row">
                <div class="col">
                    <label class="text-dark">Numero de Factura</label>
                    <input disabled class="form-control" id="colFormLabel" placeholder="FE-001-@Html.DisplayFor(model => model.invoice.id_invoice)">
                </div>
                <div class="col">
                    <label class="text-dark">Vendedor</label>
                    <input disabled class="form-control" id="colFormLabel" placeholder="@Html.DisplayFor(model => model.invoice.Users.userName)">
                </div>
                <div class="col">
                    <label class="text-dark">Fecha</label>
                    <input disabled class="form-control" id="colFormLabel" placeholder="@Html.DisplayFor(model => model.invoice.date_sell)">
                </div>
                <div class="col">
                    <label class="text-dark">Estado de Pago</label>
                    <input disabled class="form-control" id="colFormLabel" placeholder="@Html.DisplayFor(model => model.invoice.invoice_status1.invoice_status_name)">
                </div>
                <div class="col">
                    <label class="text-dark">Descuento</label>
                    <input disabled class="form-control" id="colFormLabel" placeholder="@Html.DisplayFor(model => model.invoice.payment_des)">
                </div>
            </div>

            <div class="mt-3">
                <h2>Detalles de la Compra</h2>
            </div>

            <div class="table-responsive">
                <table id="TableEmployee" class="table  table-striped ">
                    <thead class="table-dark">
                        <tr>
                            <th class="">
                                SKU
                            </th>
                            <th class="">
                                Producto
                            </th>
                            <th>
                                Marca
                            </th>
                            <th>
                                Cantidad
                            </th>
                            <th class="">
                                Precio
                            </th>
                            <th class="">
                                Acciones
                            </th>
                        </tr>
                    </thead>
                    <tbody class=" ">
                        @foreach (var item in Model.invoice_detail)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.product.product_id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.product.product_name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.product.brand_product.brand_product_name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.quantities)
                                </td>
                                <td>
                                    ₡ @Html.DisplayFor(modelItem => item.product_price)
                                </td>

                                <td>
                                    @Html.ActionLink("Ir al Producto", "Edit", "Product", new { id = item.id_invoice }, new { @class = "btn btn-primary mr-2" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>

            <div class="float-right">

                <div class="text-info  mt-4">
                    <h2><b> Total: ₡ @Html.DisplayFor(model => model.invoice.sale_total)    </b> </h2>
                </div>

            </div>


            <div class="mt-6">
                <p>
                    @Html.ActionLink("Volver a la Lista de Facturas", "Index")
                </p>
            </div>


        </div>

    </div>

FideGames/Views/Invoice/Edit.cshtml
@model FideGames.Models.invoice

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@if (ViewBag.exito == "" | ViewBag.exito == null)
{

}
else
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <span class="aria-hidden">@Html.ViewBag.exito</span>
    </div>

}
@if (ViewBag.error == "" | ViewBag.error == null)
{

}
else
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <span class="aria-hidden">@ViewBag.error</span>
    </div>

}

<div class="card-body card shadow mb-4">
    <style>
        .card-title {
            padding-bottom: 15px;
            background: #040FD9;
            color: #fff;
            padding: 16px 30px;
            min-width: 100%;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }
    </style>
    <div class="card-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>Editar Factura</h2>
            </div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.id_invoice)
        @Html.HiddenFor(model => model.seller)

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <div class="col-md-10">
                    <label class="text-dark">Factura</label>
                    <input disabled class="form-control" id="id_invoice" placeholder="FE-001-@Model.id_invoice">
                    @Html.HiddenFor(Model => Model.id_invoice)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <label class="text-dark">Cliente</label>
                    <input disabled class="form-control" id="user_id" placeholder="@Model.clients.client_name1 @Model.clients.client_name2 @Model.clients.client_lastname1 @Model.clients.client_lastname2">
                    @Html.HiddenFor(Model => Model.user_id)
                </div>
            </div>

            <div class="form-group">

                <div class="col-md-10">
                    <label class="text-dark">Monto de la Factura</label>
                    <input disabled class="form-control" id="user_id" placeholder="₡ @Model.sale_total">
                    @Html.HiddenFor(Model => Model.sale_total)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <label class="text-dark">Estado de la Factura</label>
                    @Html.DropDownListFor(mode => mode.invoice_status,new SelectList(ViewBag.Status, "Value", "Text"), "Seleccione un Estado", new { @class = "custom-select my-1 mr-sm-2" })
                    @Html.ValidationMessageFor(model => model.invoice_status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <label class="text-dark">Comentario</label>
                    @Html.EditorFor(model => model.payment_des, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.payment_des, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @{
                    int id = Model.id_invoice;
                }
                @if (Model.invoice_status == 5)
                {

                }
                else
                {
                    @Html.ActionLink("Agregar Producto", "Add", new { @id }, new { @class = "btn btn-primary mr-2" })
                }
                <button type="submit" value="Edit" class="btn btn-primary">Guardar</button>
            </div>

        </div>

    }

    <div>
        @Html.ActionLink("Volver a la Lista", "Index")
    </div>

</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

FideGames/Views/Invoice/Index.cshtml
@model IEnumerable<FideGames.Models.invoice>

@{
    ViewBag.Title = "Facturas";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@if (ViewBag.exito == "" | ViewBag.exito == null)
{

}
else
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <span class="aria-hidden">@Html.ViewBag.exito</span>
    </div>

}
@if (ViewBag.error == "" | ViewBag.error == null)
{

}
else
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <span class="aria-hidden">@ViewBag.error</span>
    </div>

}

<div class="card-body card shadow mb-4">
    <style>
        .table-title {
            padding-bottom: 15px;
            background: #040FD9;
            color: #fff;
            padding: 16px 30px;
            min-width: 100%;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }

            .table-title h2 {
                margin: 5px 0 0;
                font-size: 24px;
            }

            .table-title .btn-group {
                float: right;
            }

            .table-title .btn {
                color: #fff;
                float: right;
                font-size: 13px;
                border: none;
                min-width: 50px;
                border-radius: 2px;
                border: none;
                outline: none !important;
                margin-left: 10px;
            }
    </style>
    <div class="table-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>Lista de Facturas</h2>
            </div>
            <div class="col-sm-6">
                @Html.ActionLink("Crear Factura", "Create", null, new { @class = "btn btn-primary btn-lg" })
            </div>
        </div>

    </div>
    <div class="table-responsive">
        <table id="TableInvoice" class="table table-avance table-striped ">
            <thead class="table-dark">
                <tr>

                    <th class="">
                        Vendedor
                    </th>
                    <th>
                        Cliente
                    </th>
                    <th>
                        Fecha de Venta
                    </th>
                    <th class="">
                        Total de la Venta
                    </th>
                    <th class="">
                        Comentario
                    </th>
                    <th class="">
                        Estado del Pago
                    </th>
                    <th class="text-center">
                        Accion
                    </th>
                </tr>
            </thead>
            <tbody class=" ">
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Users.userName)
                        </td>
                        <td>
                            @{ 
                                String clienteName = item.clients.client_name1 + item.clients.client_name2;
                            }
                            @clienteName   
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.date_sell)
                        </td>
                        <td>
                            ₡ @Html.DisplayFor(modelItem => item.sale_total)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.payment_des)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.invoice_status1.invoice_status_name)
                        </td>
                        <td class="d-flex justify-content-center ">
                            @if (item.invoice_status == 5)
                            {

                            }
                            else
                            {
                                @Html.ActionLink("Editar", "Edit", new { id = item.id_invoice }, new { @class = "btn btn-primary mr-2" })
                            }
                            @Html.ActionLink("Detalle", "Details", new { id = item.id_invoice }, new { @class = "btn btn-primary" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>